stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python -m unittest discover tests

deploy:
  stage: deploy
  tags:
    - your_runner_tag
  only:
    - master
  script:
    - pip install -r requirements.txt
    - rsync -avz --delete --exclude '.git*' --exclude 'venv*' . /home/crazytimon/apps/generic_gpt_tg_bot/chatgpt_bot.py
